const UPLOAD_PICTURE = 'UPLOAD_PICTURE';
const UPLOAD_PICTURE_SUCCESS = 'UPLOAD_PICTURE_SUCCESS';
const UPLOAD_PICTURE_FAILTURE = 'UPLOAD_PICTURE_FAILTURE';

export {
  UPLOAD_PICTURE,
  UPLOAD_PICTURE_SUCCESS,
  UPLOAD_PICTURE_FAILTURE
};
