const DELETE_GAME = 'DELETE_GAME';
const DELETE_GAME_SUCCESS = 'DELETE_GAME_SUCCESS';
const DELETE_GAME_FAILTURE = 'DELETE_GAME_FAILTURE';

const GET_GAMES = 'GET_GAMES';
const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
const GET_GAMES_FAILTURE = 'GET_GAMES_FAILTURE';

const POST_GAME = 'POST_GAME';
const POST_GAME_SUCCESS = 'POST_GAME_SUCCESS';
const POST_GAME_FAILTURE = 'POST_GAME_FAILTURE';

const SET_SEARCH_BAR = 'SET_SEARCH_BAR';
const SHOW_SELECTED_GAME = 'SHOW_SELECTED_GAME';

export {
  DELETE_GAME,
  DELETE_GAME_SUCCESS,
  DELETE_GAME_FAILTURE,

  GET_GAMES,
  GET_GAMES_SUCCESS,
  GET_GAMES_FAILTURE,

  POST_GAME,
  POST_GAME_SUCCESS,
  POST_GAME_FAILTURE,

  SET_SEARCH_BAR,
  SHOW_SELECTED_GAME
};
